before_install:
  - gem update bundler rake
branches:
  only:
    - master
gemfile:
  - gemfiles/rails30.gemfile
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile
  - gemfiles/rails40.gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
notifications:
  webhooks:
    on_start: always
    urls:
      - https://buildlight.collectiveidea.com/
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - ruby-head
script: bundle exec rspec
sudo: false
