before_install:
  - gem update bundler rake
branches:
  only:
    - master
env:
  global:
    - secure: | # CODECLIMATE_REPO_TOKEN
        LANA2wEG+eJ4a+Sl0Uhw343XutMp00m/+IV4n7T+AYpFmzmBPB8k5kVP1SZR
        lhqpkdWuJlpaSUyP1EvODyS3Ryg+UtCXXKa0vX6AQseYZqMzXoWWWS1UPHx5
        R5/Dvko4JIPfOeeXwyPGnBhzewdQSqXcQR5UnPIWPG7jvfoCd/Q=
gemfile:
  - gemfiles/rails30.gemfile
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile
  - gemfiles/rails40.gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile
language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
  include:
    - rvm: 2.2.2
      gemfile: gemfiles/rails50.gemfile
      gemfile: gemfiles/rails51.gemfile
    - rvm: 2.3.0
      gemfile: gemfiles/rails50.gemfile
      gemfile: gemfiles/rails51.gemfile
notifications:
  webhooks:
    on_start: always
    urls:
      - https://buildlight.collectiveidea.com/
rvm:
  - 1.9.3
  - "2.0"
  - "2.1"
  - 2.2.2
  - 2.3.0
  - ruby-head
script: bundle exec rspec
sudo: false
