before_install:
  - gem update bundler rake
branches:
  only:
    - master
gemfile:
  - gemfiles/rails30.gemfile
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile
  - gemfiles/rails40.gemfile
language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
rvm:
  - 1.9.3
  - "2.0"
  - "2.1"
  - ruby-head
script: rspec
